"""Persistent PTY shell sessions — a REAL interactive terminal.

Self-contained: the only thing this module imports from the terminal package is
`.config`, so `terminal/` can be hosted on its own with no host app, no
database and no gateway.

Architecture mirrors the OperitTerminalCore terminal module: a single
`TerminalManager` owns every piece of terminal state and exposes it as one
reactive snapshot, instead of letting each caller track sessions on its own.

  Session management   create / switch / rename / close independent shells
  Command execution    raw keystrokes into a real TTY (`pty.fork()`)
  State management     session id, label, cwd, size, uptime, exit state —
                       one snapshot (`TerminalManager.snapshot()`), streamed
                       to clients over SSE
  Event notification   output, working-directory changes and shell exit are
                       emitted as discrete events, not just appended bytes

Each session spawns the system shell (`/bin/bash`, fallback `sh`) on a
pseudo-terminal, so programs that need a TTY behave exactly as on a local
machine: `ssh` prompts for host keys, `git clone` asks for credentials,
`sudo` requests a password, `vim` renders full-screen.

The shell reports its working directory through OSC 7 (emitted from
`PROMPT_COMMAND`), which the reader thread parses — so `cd` inside a session
is reflected in the session list without the browser guessing it.

Idle sessions are reaped; everything is torn down on app shutdown.
"""
from __future__ import annotations

import fcntl
import os
import pty
import re
import select
import shlex
import signal
import struct
import threading
import time
from urllib.parse import unquote

from .config import PACKAGE_ROOT, build_root, engine_runtime

SESSION_TTL_S = 30 * 60          # idle reaper
SCROLLBACK_BYTES = 512 * 1024    # per-session history kept for late attachers
READ_CHUNK = 4096
MAX_SESSIONS = 8                 # hard cap — every session is a real process
AGENT_LABEL_PREFIX = "agent"    # every autonomous-agent tab is labelled with this
AGENT_SESSION_LABEL = "agent"    # the bare label; agent_session() adds the goal
AGENT_RUN_TIMEOUT_S = 45         # how long one agent command may hold the session

# OSC 7 — "current working directory" report. Emitted by the shell before
# every prompt, parsed here so the session list always shows a real path.
_OSC7_RE = re.compile(rb"\x1b\]7;file://[^\x07\x1b]*(\x07|\x1b\\)")
_OSC7_PREFIX_LEN = len(b"\x1b]7;file://")
_OSC7_TAIL = 256      # bytes kept across reads so a split OSC 7 still parses

# The prompt the session shell shows — the permanent AgentLinux identity of
# the cloud shell. `\[\]` keeps escape sequences from counting toward the
# prompt width. Rendered: `~ AgentLinux:~#` (green brand, blue path, `#`
# because every session runs as root).
_PROMPT = r"\[\033[1;32m\]~ AgentLinux\[\033[0m\]:\[\033[1;34m\]\w\[\033[0m\]# "

# Shown once per shell, right before the first prompt — states plainly what
# this terminal is and what stays available in it.
_MOTD = (
    "Agent_Linux Cloud Shell — Debian Linux, root access, permanent session.\r\n"
    "Tools stay installed for you and for background agent tasks: git, curl, python3, pip,\r\n"
    "node, bun, npm. Storage targets (Cloudflare R2 / GCS / AWS S3 / more) are managed\r\n"
    "from the Nova Console panel. Type `nova help` for gateway commands.\r\n"
)

# OSC 7 (cwd report) plus a one-time MOTD. Both run from PROMPT_COMMAND so
# every attaching client sees them in the scrollback; the marker file keeps
# the MOTD from repeating before every prompt.
_MOTD_ONE_LINE = _MOTD.replace("\r\n", " | ").rstrip(" |\r\n")
_OSC7_AND_MOTD = (
    "printf '\\033]7;file://%s%s\\007' \"$(hostname)\" \"$PWD\"; "
    "if [ ! -f /tmp/.nova_motd_$$ ]; then printf '\\r\\n%s\\r\\n' "
    + shlex.quote(_MOTD_ONE_LINE)
    + "; touch /tmp/.nova_motd_$$; fi"
)

# Kept for the `sh` fallback path (bash below uses the rcfile).
_OSC7_PROMPT_COMMAND = _OSC7_AND_MOTD

# Per-session bash rc — guarantees the AgentLinux prompt and the one-time
# MOTD even when the image's own /root/.bashrc would overwrite PS1.
_BASHRC = (
    "# Generated by agent_linux/pty.py — the permanent AgentLinux shell config.\n"
    "export AGENT_LINUX_GATEWAY=1\n"
    "export PS1=" + shlex.quote(_PROMPT) + "\n"
    "export PROMPT_COMMAND=" + shlex.quote(_OSC7_AND_MOTD) + "\n"
)


def _default_label(cwd: str) -> str:
    """Tabs read better as `ui` than as `/srv/nova/ui`."""
    name = os.path.basename(os.path.normpath(cwd or ""))
    return name or "root"


class TerminalSession:
    """One independent shell: its own PTY, scrollback, cwd and lifecycle."""

    def __init__(self, session_id: str, cwd: str = "", cols: int = 120, rows: int = 32,
                 label: str = "", argv: list[str] | None = None,
                 env: dict[str, str] | None = None):
        self.id = session_id
        self.created_at = time.time()
        self.last_activity = self.created_at
        self.lock = threading.Lock()
        self.buffer = bytearray()
        self.total = 0                  # bytes ever produced (trim-safe cursor)
        self.closed = False
        self.exit_code: int | None = None
        self.named = bool(label)        # True once the user renamed the tab
        self.cwd = cwd if cwd and os.path.isdir(cwd) else str(PACKAGE_ROOT)
        self.label = label.strip() or _default_label(self.cwd)
        self.cols = max(20, min(500, int(cols or 120)))
        self.rows = max(5, min(200, int(rows or 32)))
        # A session is normally an interactive bash. `argv` lets it be something
        # else on the same PTY — an `ssh` client, most importantly — so a remote
        # connection is a real tab the user can watch and type into, rather than
        # a subprocess whose output has to be proxied. `env` is layered on top of
        # the shell environment for the same reason (SSH_ASKPASS, config paths).
        self.argv = list(argv) if argv else None
        self.extra_env = dict(env or {})

        self._osc_tail = b""
        self.pid, self.master = pty.fork()
        if self.pid == 0:  # child — exec the shell (or the requested command)
            try:
                os.chdir(self.cwd)
            except OSError:
                pass
            os.environ["TERM"] = os.environ.get("TERM") or "xterm-256color"
            # Permanent cloud-shell identity: Debian root, HOME /root, and a
            # stable hostname so `~ AgentLinux` is true, not cosmetic.
            os.environ["HOME"] = "/root"
            os.environ["USER"] = "root"
            os.environ["LOGNAME"] = "root"
            os.environ["SHELL"] = "/bin/bash"
            os.environ["HOSTNAME"] = "agent-linux"
            os.environ["PS1"] = _PROMPT
            os.environ["PROMPT_COMMAND"] = _OSC7_PROMPT_COMMAND
            os.environ["AGENT_LINUX_GATEWAY"] = "1"
            os.environ.update(self.extra_env)
            if self.argv:
                # The command owns the PTY: no rcfile, no prompt, no MOTD —
                # `ssh` draws its own UI and expects a clean terminal.
                try:
                    os.execvp(self.argv[0], self.argv)
                except OSError:
                    os._exit(127)
            # Preferred path: bash with our rcfile, so the branded prompt and
            # MOTD always win over the image's /root/.bashrc.
            try:
                rcfile = f"/tmp/.agent_linux_bashrc_{os.getpid()}.rc"
                with open(rcfile, "w", encoding="utf-8") as fh:
                    fh.write(_BASHRC)
                os.execv("/bin/bash", ["/bin/bash", "--rcfile", rcfile, "-i"])
            except OSError:
                pass
            for shell in ("/bin/bash", "/bin/sh"):
                try:
                    os.execv(shell, [shell, "-i"])
                except OSError:
                    continue
            os._exit(127)

        # Parent: size the pty and make reads non-blocking.
        self._resize_fd(self.cols, self.rows)
        flags = fcntl.fcntl(self.master, fcntl.F_GETFL)
        fcntl.fcntl(self.master, fcntl.F_SETFL, flags | os.O_NONBLOCK)

        self.reader = threading.Thread(target=self._read_loop, daemon=True, name=f"pty-{session_id}")
        self.reader.start()

    # ------------------------------------------------------------------ #
    # Output stream
    # ------------------------------------------------------------------ #

    def _append(self, data: bytes) -> None:
        with self.lock:
            self.buffer.extend(data)
            self.total += len(data)
            if len(self.buffer) > SCROLLBACK_BYTES:
                del self.buffer[: len(self.buffer) - SCROLLBACK_BYTES]

    def _track_cwd(self, data: bytes) -> None:
        """Parse OSC 7 so the session list reflects real `cd` navigation."""
        window = self._osc_tail + data
        # The shell reports before every prompt, so a chunk can carry several
        # reports (and the retained tail may end mid-sequence). Take the last
        # complete one and resume from just after it.
        last = None
        for match in _OSC7_RE.finditer(window):
            last = match
        self._osc_tail = window[last.end():] if last else window[-_OSC7_TAIL:]
        if last is None:
            return
        try:
            # Drop the `\x1b]7;file://` prefix and the BEL / ST terminator,
            # then the host part — OSC 7 is `file://<host><absolute path>`.
            rest = last.group(0)[_OSC7_PREFIX_LEN:].rstrip(b"\x07")
            rest = rest.rsplit(b"\x1b\\", 1)[0]
            if not rest.startswith(b"/"):
                parts = rest.split(b"/", 1)
                rest = b"/" + parts[1] if len(parts) == 2 else b"/"
            resolved = unquote(rest.decode("utf-8", "replace"))
        except Exception:
            return
        if resolved and os.path.isdir(resolved):
            with self.lock:
                if resolved != self.cwd:
                    self.cwd = resolved
                    if not self.named:
                        self.label = _default_label(resolved)

    def _read_loop(self) -> None:
        while not self.closed:
            try:
                ready, _, _ = select.select([self.master], [], [], 0.25)
            except (OSError, ValueError):
                break
            if not ready:
                if self._exited():
                    break
                continue
            try:
                data = os.read(self.master, READ_CHUNK)
            except BlockingIOError:
                continue
            except OSError:
                break
            if not data:
                break
            self.last_activity = time.time()
            self._track_cwd(data)
            self._append(data)
        self._append(f"\r\n\x1b[90m[session {self.label} ended]\x1b[0m\r\n".encode())
        self.exit_code = self._reap_exit_code()
        self.closed = True

    def _exited(self) -> bool:
        try:
            pid, _ = os.waitpid(self.pid, os.WNOHANG)
        except ChildProcessError:
            return True
        return pid == self.pid

    def _reap_exit_code(self) -> int:
        try:
            _, status = os.waitpid(self.pid, os.WNOHANG)
        except ChildProcessError:
            return 0
        if os.WIFEXITED(status):
            return os.WEXITSTATUS(status)
        return 0

    # ------------------------------------------------------------------ #
    # Input
    # ------------------------------------------------------------------ #

    def write(self, data: str) -> None:
        """Feed keystrokes (raw, may include \\r, \\u0003 for Ctrl+C …)."""
        if self.closed:
            raise RuntimeError("session closed")
        self.last_activity = time.time()
        try:
            os.write(self.master, data.encode("utf-8", errors="replace"))
        except OSError as err:
            raise RuntimeError(f"session write failed: {err}") from err

    def resize(self, cols: int, rows: int) -> None:
        self.cols = max(20, min(500, int(cols or self.cols)))
        self.rows = max(5, min(200, int(rows or self.rows)))
        self._resize_fd(self.cols, self.rows)

    def _resize_fd(self, cols: int, rows: int) -> None:
        try:
            winsize = struct.pack("HHHH", rows, cols, 0, 0)
            fcntl.ioctl(self.master, 1, winsize)  # TIOCSWINSZ
            os.kill(self.pid, signal.SIGWINCH)
        except (OSError, ValueError):
            pass

    # ------------------------------------------------------------------ #
    # State
    # ------------------------------------------------------------------ #

    def touch(self) -> None:
        self.last_activity = time.time()

    def snapshot(self, since: int = 0) -> tuple[bytes, int]:
        """Bytes produced after `since`, plus the new cursor position.

        `since` is a total-bytes counter, not a buffer index, so it stays
        correct after the scrollback ring trims old output.
        """
        with self.lock:
            start = max(0, self.total - len(self.buffer))
            begin = max(start, int(since or 0))
            return bytes(self.buffer[begin - start:]), self.total

    def info(self, active: bool = False) -> dict:
        with self.lock:
            return {
                "id": self.id,
                "label": self.label,
                "cwd": self.cwd,
                "active": active,
                "closed": self.closed,
                "pid": self.pid,
                "exit_code": self.exit_code,
                "created_at": self.created_at,
                "last_activity": self.last_activity,
                "idle_s": int(max(0, time.time() - self.last_activity)),
                "cols": self.cols,
                "rows": self.rows,
                "buffer_size": len(self.buffer),
            }

    def stop(self) -> None:
        if self.closed:
            return
        try:
            os.remove(f"/tmp/.nova_bashrc_{self.pid}.rc")
        except OSError:
            pass
        try:
            os.kill(self.pid, signal.SIGHUP)
        except OSError:
            pass
        time.sleep(0.1)
        if not self._exited():
            try:
                os.kill(self.pid, signal.SIGKILL)
            except OSError:
                pass
        self.closed = True
        try:
            os.close(self.master)
        except OSError:
            pass


class SessionLimitReached(RuntimeError):
    """Raised when a new session is requested while MAX_SESSIONS are live."""


class TerminalManager:
    """Single source of truth for every terminal session on this server."""

    def __init__(self, max_sessions: int = MAX_SESSIONS):
        self._sessions: dict[str, TerminalSession] = {}
        self._active: str | None = None
        self._lock = threading.Lock()
        self._counter = 0
        self._max = max_sessions
        self._reaper_started = False

    # --------------------------- lifecycle --------------------------- #

    def _reap_loop(self) -> None:
        while True:
            time.sleep(60)
            now = time.time()
            dead: list[TerminalSession] = []
            with self._lock:
                stale = [
                    sid for sid, s in self._sessions.items()
                    if s.closed or now - s.last_activity > SESSION_TTL_S
                ]
                for sid in stale:
                    dead.append(self._sessions.pop(sid))
                    if self._active == sid:
                        self._active = next(reversed(list(self._sessions)), None)
            for session in dead:
                session.stop()

    def start_reaper(self) -> None:
        with self._lock:
            if self._reaper_started:
                return
            self._reaper_started = True
        threading.Thread(target=self._reap_loop, daemon=True, name="pty-reaper").start()

    # ---------------------------- sessions ---------------------------- #

    def create(self, cwd: str = "", cols: int = 120, rows: int = 32,
               label: str = "", argv: list[str] | None = None,
               env: dict[str, str] | None = None) -> TerminalSession:
        self.start_reaper()
        with self._lock:
            if len(self._sessions) >= self._max:
                raise SessionLimitReached(
                    f"the limit of {self._max} concurrent sessions is reached — "
                    "close a tab before opening another one"
                )
            self._counter += 1
            session_id = f"pty-{int(time.time())}-{self._counter}"
            session = TerminalSession(session_id, cwd=cwd, cols=cols, rows=rows,
                                      label=label, argv=argv, env=env)
            self._sessions[session_id] = session
            self._active = session_id
            return session

    def get(self, session_id: str | None) -> TerminalSession | None:
        if not session_id:
            return None
        with self._lock:
            return self._sessions.get(session_id)

    def close(self, session_id: str) -> bool:
        """Close a session and hand focus to the next one, if any."""
        with self._lock:
            session = self._sessions.pop(session_id, None)
            if session is None:
                return False
            if self._active == session_id:
                self._active = next(reversed(list(self._sessions)), None)
        session.stop()
        return True

    def close_all(self) -> None:
        with self._lock:
            sessions = list(self._sessions.values())
            self._sessions.clear()
            self._active = None
        for session in sessions:
            session.stop()

    def activate(self, session_id: str) -> TerminalSession | None:
        """Switch the focused session (creating it is not implied)."""
        with self._lock:
            session = self._sessions.get(session_id)
            if session is not None and not session.closed:
                self._active = session_id
        return session

    def rename(self, session_id: str, label: str) -> TerminalSession | None:
        clean = " ".join((label or "").split())[:40]
        with self._lock:
            session = self._sessions.get(session_id)
            if session is None:
                return None
            session.label = clean or session.label
            session.named = bool(clean)
        return session

    @property
    def active_id(self) -> str | None:
        with self._lock:
            return self._active

    def snapshot(self) -> dict:
        """Everything a client needs to render the whole terminal state."""
        with self._lock:
            active = self._active
            return {
                "active": active,
                "max_sessions": self._max,
                "sessions": [
                    s.info(active=s.id == active) for s in self._sessions.values()
                ],
            }

    def list_sessions(self) -> list[dict]:
        return self.snapshot()["sessions"]


# --------------------------------------------------------------------------- #
# Process-wide manager + compatibility helpers
# --------------------------------------------------------------------------- #

manager = TerminalManager()


def stop_all() -> None:
    """Shutdown hook — every shell is torn down with the gateway process."""
    manager.close_all()


def engine_banner() -> str | None:
    """One extra MOTD line describing the NovaFree engine runtime, or None."""
    runtime = engine_runtime()
    return f"NovaFree engine runtime: {runtime} (sidecar auto-starts with the gateway)." if runtime else None


def ensure_default() -> None:
    """Keep the permanent AgentLinux cloud shell alive.

    The cloud terminal always presents a ready root shell: if no live session
    exists (first boot, or the idle reaper collected an unused one), a default
    `AgentLinux` session is created so agent tasks and users always have a
    terminal to run in. Sessions start in the builder workspace base
    location (`/app/build`) — deliberately separate from the gateway's own
    project files. Existing sessions are left untouched.
    """
    with manager._lock:  # noqa: SLF001 — single-owner check under the manager lock
        live = [s for s in manager._sessions.values() if not s.closed]
    if live:
        return
    try:
        cwd = str(build_root())
    except Exception:
        cwd = str(PACKAGE_ROOT)
    try:
        manager.create(cwd=cwd, cols=120, rows=32, label="AgentLinux")
    except (SessionLimitReached, OSError):
        pass


_ANSI_RE = re.compile(rb"\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)|\x1b[@-Z\\-_]|\x1b\[[0-?]*[ -/]*[@-~]|\r")


def strip_ansi(data: bytes | str) -> str:
    """Plain text for a tool result — the terminal keeps the raw bytes."""
    raw = data.encode("utf-8", errors="replace") if isinstance(data, str) else data
    return _ANSI_RE.sub(b"", raw).decode("utf-8", errors="replace")


def agent_label(goal: str) -> str:
    """Tab label for one agent task: `agent` plus enough of the goal that two
    tasks are tellable apart in the session strip."""
    flat = " ".join((goal or "").split())[:28].strip()
    return f"{AGENT_SESSION_LABEL} \u00b7 {flat}" if flat else AGENT_SESSION_LABEL


def is_agent_label(label: str) -> bool:
    return (label or "").split("\u00b7")[0].strip() == AGENT_SESSION_LABEL


def agent_session(label: str | None = None) -> TerminalSession | None:
    """The live PTY session the agent types its commands into.

    Agent tasks are far easier to trust when you can watch them: this is a
    real `AgentLinux` shell, listed in the session tabs like any other. It is
    a dedicated session rather than the user's focused one so an agent command
    can never land in the middle of something you were typing.

    One tab per task: `label` identifies the task, so every step of that task
    reuses its own shell (state has to survive between steps) while the next
    task opens a fresh tab of its own. When the session cap is hit we fall back
    to the newest agent tab, then to whichever session is focused.
    """
    label = (label or "").strip()
    with manager._lock:  # noqa: SLF001 - single-owner read under the manager lock
        agent_tabs = [s for s in manager._sessions.values()
                      if not s.closed and is_agent_label(s.label)]
        newest = max(agent_tabs, key=lambda s: s.created_at, default=None)
        if label:
            for s in agent_tabs:
                if s.label == label:
                    return s             # a later step of the same task
        elif newest is not None:
            return newest                # no task context: keep using one tab
    try:
        cwd = str(build_root())
    except Exception:
        cwd = str(PACKAGE_ROOT)
    for attempt in (0, 1, 2):
        try:
            return manager.create(cwd=cwd, cols=120, rows=32,
                                  label=label or AGENT_SESSION_LABEL)
        except SessionLimitReached:
            if attempt == 0 and newest is not None:
                return newest                  # reuse the last agent tab
            if attempt == 1:
                return manager.get(manager.active_id)
        except OSError:
            return None
    return None


def run_in_session(session: TerminalSession, command: str,
                   timeout: int = AGENT_RUN_TIMEOUT_S) -> tuple[str, int]:
    """Type `command` into a live session and read the real output back.

    The command is wrapped in a unique sentinel echo, so completion is known
    exactly instead of guessed from a prompt string, and the exit code comes
    back for free. Everything printed stays in the session buffer, so what the
    user watches in the tab is byte-for-byte what the agent gets.

    Returns (output, exit_code); exit_code is -1 when the command timed out.
    """
    cmd = (command or "").strip()
    if not cmd or session.closed:
        return "", -1
    # The marker is printed from two separate words on purpose. A single
    # literal token would also appear in the PTY's *echo* of the command we
    # just typed, so the wait below would finish before the command ran.
    nonce = str(int(time.time() * 1000) % 1_000_000)
    token = f"AGENT_LINUX_DONE_{nonce}"
    start = session.total
    session.write(cmd + "\n")
    session.write(f"printf '\\n%s%s:%s\\n' AGENT_LINUX_DONE_ {nonce} \"$?\"\n")

    deadline = time.time() + max(1, timeout)
    tail = ""
    while time.time() < deadline:
        time.sleep(0.05)
        chunk, _ = session.snapshot(since=start)
        tail = chunk.decode("utf-8", errors="replace")
        if token + ":" in tail:
            break

    head, sep, rest = tail.partition(token + ":")
    if not sep:
        return _clean_run_output(strip_ansi(tail), cmd, nonce), -1
    code_raw, _, _ = rest.partition("\n")
    try:
        code = int(code_raw.strip() or 0)
    except ValueError:
        code = -1
    return _clean_run_output(strip_ansi(head), cmd, nonce), code


_PROMPT_PREFIX_RE = re.compile(r"^(?:~[ \t]*)?Root@\S*#[ \t]*")
_TRAILING_PROMPT_RE = re.compile(r"(?:~[ \t]*)?Root@\S*#[ \t]*$")


def _marker_echo(nonce: str) -> str:
    """The exact text `run_in_session` types to print the completion marker."""
    return f"printf '\\n%s%s:%s\\n' AGENT_LINUX_DONE_ {nonce} \"$?\""


def _command_echo_line(lines: list[str], cmd: str) -> int:
    """Index of the first line that is our command's own echo.

    A freshly started shell prefixes the echo with its prompt; an already
    running one only echoes the raw bytes we wrote. Prefer the prompted copy
    (it lands after the banner), and fall back to the raw echo, which is
    always written before the output it precedes.
    """
    prompted = [
        i for i, line in enumerate(lines)
        if (m := _PROMPT_PREFIX_RE.match(line.strip()))
        and line.strip()[m.end():].strip() == cmd
    ]
    if prompted:
        return prompted[-1] + 1
    for i, line in enumerate(lines):
        if line.strip() == cmd:
            return i + 1
    return 0


def _clean_run_output(head: str, cmd: str, nonce: str) -> str:
    """Strip the tty chrome so the agent only sees what the command printed.

    A raw capture is noisy: the shell banner, the command echoed once by the
    tty and again by the shell, the marker `printf` echoed the same two ways,
    and the prompt printed again after the output. The command's own echo is
    the divider, and cutting every line at the marker echo removes whatever the
    shell printed to run the command — so what is left is the output itself.
    """
    marker = _marker_echo(nonce)
    lines = head.replace("\r\n", "\n").replace("\r", "").split("\n")
    kept: list[str] = []
    for line in lines[_command_echo_line(lines, cmd):]:
        at = line.find(marker)
        if at != -1:
            line = line[:at]                      # drop the echoed marker printf
        line = _TRAILING_PROMPT_RE.sub("", line).rstrip()
        if line.strip():
            kept.append(line)
    return "\n".join(kept).strip()


def shell_hint(cmd: str) -> str | None:
    """One-shot exec hint: TTY-requiring flows need the live terminal."""
    try:
        parts = shlex.split(cmd)
    except ValueError:
        parts = cmd.split()
    first = parts[0] if parts else ""
    if first in ("ssh", "sftp", "scp"):
        return (
            "ssh needs an interactive terminal for host-key and password prompts — "
            "open a session tab and run it there."
        )
    if first == "git" and any(flag in cmd for flag in ("clone", "push", "pull", "fetch")) \
            and "https://" in cmd:
        return (
            "Private git over HTTPS asks for credentials — run it in a session tab, "
            "where the username and password prompt works, or use a token URL."
        )
    return None
